---
- name: Configure Web Server and Install Docker and Node Exporter
  hosts: webserver # run on all hosts listen under [webserver] group in inventory.ini

  become: yes # Execute all tasks as the root user

  gather_facts: no

  pre_tasks:
    - name: Ensure .ssh directory exists
      delegate_to: localhost
      become: no
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '0700'
      changed_when: false
    
    - name: Add SSH host key to known_hosts
      delegate_to: localhost
      become: no
      ansible.builtin.shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts" # append host key to known_hosts so that ansible doesn't stop with a prompt
      changed_when: "shell_result.rc != 0"
      register: shell_result
      ignore_errors: yes

  roles:
    - role: prometheus.prometheus.node_exporter

  
  tasks:
    - name: Manually gather sever facts
      ansible.builtin.setup: {}
      
    - name: Wait 60 seconds for SSH to become available after server boot
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Update apt package cache
      ansible.builtin.apt: # it's like apt-get update
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present # check if present, if not install it
      register: apt_install_docker
      until: apt_install_docker is not failed
      retries: 5
      delay: 10

    - name: Ensure Docker service is running and enabled on boot
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Run Hello-Worldapp container
      ansible.builtin.docker_container:
        name: hello-world-app
        image: "ghcr.io/mayyyk/devops_playground:latest"
        state: started
        pull: yes # Forces docker to pull lates version from registry
        restart_policy: always
        ports:
          - "5000:5000"
  
