--- 
- name: Configure K3s Master
  hosts: k3s_master
  become: yes # execute tasks as root
  gather_facts: yes
  roles:
    - role: prometheus.prometheus.node_exporter
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install K3s server
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io | sh -s - 
        --write-kubeconfig-mode 644 
        --disable traefik 
        --node-name k3s-master
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Fetch K3s token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Store K3s token
      ansible.builtin.set_fact:
        k3s_join_token: "{{ k3s_token['content'] | b64decode | trim }}"

- name: Configure K3s Workers
  hosts: k3s_workers
  become: yes
  gather_facts: yes
  roles:
    - role: prometheus.prometheus.node_exporter
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install K3s agent on worker nodes
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ groups['k3s_master'][0] }}:6443 
        K3S_TOKEN={{ hostvars[groups['k3s_master'][0]]['k3s_join_token'] }} 
        sh -s - --node-name k3s-worker-{{ ansible_play_batch.index(inventory_hostname) + 1 }}
      args:
        creates: /etc/rancher/k3s/k3s.yaml
